// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcSUSWEKS27Jmih_GcpsPYta2VwSxdOhM',
    appId: '1:363020026305:web:7f38273ac62e11d9fe6f40',
    messagingSenderId: '363020026305',
    projectId: 'flutter-social-9683f',
    authDomain: 'flutter-social-9683f.firebaseapp.com',
    storageBucket: 'flutter-social-9683f.appspot.com',
    measurementId: 'G-3TYGX59VP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmCQAZcLKu0jioQHkgspt4ytO-5dXgp3E',
    appId: '1:363020026305:android:c254396aff2b3e7ffe6f40',
    messagingSenderId: '363020026305',
    projectId: 'flutter-social-9683f',
    storageBucket: 'flutter-social-9683f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgkeVUEhkqi_87DQzrvdKipC-1blYkPos',
    appId: '1:363020026305:ios:e9480050e890152cfe6f40',
    messagingSenderId: '363020026305',
    projectId: 'flutter-social-9683f',
    storageBucket: 'flutter-social-9683f.appspot.com',
    iosClientId: '363020026305-ocibkj64oqlth6k9ofm7g4rafg52h229.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSocial',
  );
}
